spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AAA
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

oauthKey: 187Pd7q12FgqNqIm63-qrghGH38CJAIrHdueGxjuvi6YEbd2kGmAGuP/Q8HJ3HJq

server:
  port: 9000
  error:
    include-stacktrace: on_trace_param


