package com.aaa.automaticanalyzer.processingengine;

import com.aaa.automaticanalyzer.model.Disease;
import com.aaa.automaticanalyzer.model.Medication;
import com.aaa.automaticanalyzer.model.Medicine;
import com.aaa.automaticanalyzer.model.User;
import com.aaa.automaticanalyzer.model.analysis.BaseAnalysis;
import com.aaa.automaticanalyzer.model.analysis.HypothyroidismAnalysis;

import java.util.Arrays;
import java.util.List;

public class HypothyroidismEngine implements ProcessingEngine {

    /*  Doses for eutirox are the following: 25, 50, 75, 88, 100, 112, 125, 137, 150, 175, 200
        The changes in medication are generated by using the last dose taken, so if you were taking 25mg
        and the blood test shows a TSH over 4.78 you will start taking 50mg and so on.
     */

    @Override
    public List<Medicine> generateMedication(BaseAnalysis analysis) {
        Medicine medicine = new Medicine();
        medicine.setDose(25d);
        medicine.setName("Eutirox");
        return Arrays.asList(medicine);
    }

    @Override
    public List<Medicine> increaseMedication(List<Medication> medication) {
        Medicine medicine = new Medicine();
        medicine.setName("Eutirox");

        return null;
    }

    @Override
    public List<Medicine> decreaseMedication(List<Medication> medications) {
        return null;
    }

    @Override
    public List<Medicine> modifyMedication(User user, BaseAnalysis analysis) {
        HypothyroidismAnalysis htAnalysis = (HypothyroidismAnalysis) analysis;
        if (Double.parseDouble(htAnalysis.getTSH()) > Double.parseDouble(htAnalysis.getMaxTSH())) {
            if (user.isMedicated(Disease.HYPOTHYROIDISM))
                return increaseMedication(user.getMedications());
            else
                return generateMedication(analysis);
        }

        if (Double.parseDouble(htAnalysis.getTSH()) < Double.parseDouble(htAnalysis.getMaxTSH())) {
            //hyperthyroidism
        }
        return null;
    }
}
